import { AuditLogEntry } from '@/types/audit';
export const INITIAL_AUDIT_LOGS: AuditLogEntry[] = [
  {
    id: 'log_001',
    timestamp: '2026-07-24 09:15:30',
    actor_name: 'Super Admin',
    actor_username: 'admin',
    actor_role: 'SUPER_ADMIN',
    action_type: 'MASK_UNMASK',
    action_description: 'Gỡ bảo mật Mask hiển thị SĐT, MST và CCCD danh sách Khách hàng',
    resource_module: 'CUSTOMERS_360',
    ip_address: '192.168.1.102',
    device_info: 'Chrome 126.0 (Windows 11)',
    severity: 'WARNING',
  },
  {
    id: 'log_002',
    timestamp: '2026-07-24 08:54:12',
    actor_name: 'Phạm Minh Đức',
    actor_username: 'ducpm',
    actor_role: 'SALES_MANAGER',
    action_type: 'EXPORT_EXCEL',
    action_description: 'Xuất file Excel báo cáo tổng hợp danh sách 1.240 Khách hàng CRM',
    resource_module: 'CUSTOMERS_360',
    ip_address: '192.168.1.115',
    device_info: 'Chrome 126.0 (macOS Sonoma)',
    severity: 'INFO',
  },
  {
    id: 'log_003',
    timestamp: '2026-07-24 07:30:00',
    actor_name: 'Super Admin',
    actor_username: 'admin',
    actor_role: 'SUPER_ADMIN',
    action_type: 'RBAC_UPDATE',
    action_description: 'Cập nhật ma trận phân quyền 2 chiều cho vai trò CSKH Specialist',
    resource_module: 'RBAC_SETTINGS',
    ip_address: '192.168.1.102',
    device_info: 'Chrome 126.0 (Windows 11)',
    severity: 'CRITICAL',
  },
  {
    id: 'log_004',
    timestamp: '2026-07-23 16:45:20',
    actor_name: 'Trần Văn Hoàng',
    actor_username: 'hoangtv',
    actor_role: 'SALES_REP',
    action_type: 'LEAD_STAGE_CHANGE',
    action_description: 'Chuyển trạng thái Lead LD-2026-0811 từ [Khảo Sát Gian Hàng] ➔ [Chốt Hợp Đồng]',
    resource_module: 'LEADS_PIPELINE',
    ip_address: '192.168.1.140',
    device_info: 'Edge 126.0 (Windows 11)',
    severity: 'INFO',
  },
];
