import { ChatConversation, QuickReplyMacro } from '@/types';
export const DEFAULT_QUICK_REPLIES: QuickReplyMacro[] = [
  {
    id: 'macro_1',
    title: 'Tư vấn Gói Gian Hàng Shopee Mall',
    category: 'Gói Dịch Vụ',
    content: 'Chào bạn, gói Dịch Vụ Vận Hành Gian Hàng Shopee Mall của GGBingo bao gồm: Thiết kế trang trí gian hàng chuẩn SEO, Đăng tải 50+ sản phẩm, Tối ưu từ khóa Ads và Cam kết GMV tăng trưởng 200%. Bạn có muốn nhận file báo giá chi tiết không ạ?',
  },
  {
    id: 'macro_2',
    title: 'Gửi Bảng Giá Dịch Vụ TikTok Shop',
    category: 'Báo Giá',
    content: 'Dạ xin gửi bạn Báo giá Gói TikTok Shop Partner (TSP): Phí khởi tạo 15.000.000đ/tháng (gồm 8 Video ngắn/tháng + 4 Phiên Livestream chuyên nghiệp). Bạn cho bên mình xin SĐT để chuyên viên gọi tư vấn nhé!',
  },
  {
    id: 'macro_3',
    title: 'Hướng Dẫn Quy Trình Ký Hợp Đồng',
    category: 'Hợp Đồng',
    content: 'Chào anh/chị, quy trình ký HĐLĐ/Hợp đồng Dịch vụ tại GGBingo rất nhanh chóng: 1. Xem trước file PDF Cloudflare R2 ➔ 2. Ký số điện tử ➔ 3. Hệ thống tự động kích hoạt tài khoản CRM và gửi bản sao qua Email ạ.',
  },
  {
    id: 'macro_4',
    title: 'Hỗ Trợ Gian Hàng GGBingoVN Platform',
    category: 'Hỗ Trợ Gian Hàng',
    content: 'Xin chào, để mở gian hàng chính thức trên nền tảng GGBingoVN E-Commerce, anh/chị chỉ cần cung cấp Giấy ĐKKD hoặc CCCD chính chủ. Em sẽ hỗ trợ duyệt nhanh trong 15 phút ạ!',
  },
];

export const INITIAL_CHAT_CONVERSATIONS: ChatConversation[] = [
  {
    id: 'chat_001',
    channel_type: 'ZALO_OA',
    channel_name: 'Zalo OA GGBingo Official',
    customer_name: 'Nguyễn Hồng Lực',
    customer_phone: '0988****111',
    customer_email: 'luc.nguyen@logistics.vn',
    crm_customer_id: 'cust_001', // Linked to existing customer
    assigned_rep_name: 'Trần Văn Hoàng (Sale Exec)',
    unread_count: 0,
    status: 'IN_PROGRESS',
    tags: ['Vận Tải', 'Shopee Mall', 'Enterprise'],
    last_message: 'Anh cần hỏi quy trình gia hạn gói vận hành Shopee Mall quý tới.',
    last_message_at: '10:15',
    messages: [
      {
        id: 'm1',
        conversation_id: 'chat_001',
        sender_type: 'CUSTOMER',
        sender_name: 'Nguyễn Hồng Lực',
        content: 'Chào GGBingo, gian hàng Vận Tải Hồng Lực đợt này chạy Shopee Ads rất mượt.',
        timestamp: '10:00',
        is_read: true,
      },
      {
        id: 'm2',
        conversation_id: 'chat_001',
        sender_type: 'AGENT',
        sender_name: 'Trần Văn Hoàng (Sale Exec)',
        content: 'Dạ chào anh Lực! Cảm ơn anh đã tin tưởng dịch vụ. Team vận hành vừa tối ưu bộ từ khóa doanh số tăng 35% đấy ạ.',
        timestamp: '10:05',
        is_read: true,
      },
      {
        id: 'm3',
        conversation_id: 'chat_001',
        sender_type: 'CUSTOMER',
        sender_name: 'Nguyễn Hồng Lực',
        content: 'Anh cần hỏi quy trình gia hạn gói vận hành Shopee Mall quý tới.',
        timestamp: '10:15',
        is_read: true,
      },
    ],
  },
  {
    id: 'chat_002',
    channel_type: 'FACEBOOK_FANPAGE',
    channel_name: 'Fanpage GGBingo E-Commerce Solutions',
    customer_name: 'Trần Bảo An',
    customer_phone: '0988666888',
    customer_email: 'baoan.tran@beauty.vn',
    crm_customer_id: undefined, // New potential customer!
    assigned_rep_name: 'Nguyễn Quốc Tuấn (Sale Senior)',
    unread_count: 2,
    status: 'UNREAD',
    tags: ['Tư vấn TikTok Shop', 'Chưa có CRM'],
    last_message: 'Bên em có gói quay Video ngắn đăng TikTok Shop kèm Livestream không?',
    last_message_at: '10:30',
    messages: [
      {
        id: 'm4',
        conversation_id: 'chat_002',
        sender_type: 'CUSTOMER',
        sender_name: 'Trần Bảo An',
        content: 'Chào admin, thương hiệu Mỹ Phẩm Bảo An của mình muốn chạy gian hàng TikTok Shop.',
        timestamp: '10:28',
        is_read: false,
      },
      {
        id: 'm5',
        conversation_id: 'chat_002',
        sender_type: 'CUSTOMER',
        sender_name: 'Trần Bảo An',
        content: 'Bên em có gói quay Video ngắn đăng TikTok Shop kèm Livestream không?',
        timestamp: '10:30',
        is_read: false,
      },
    ],
  },
  {
    id: 'chat_003',
    channel_type: 'ZALO_PERSONAL',
    channel_name: 'Zalo Cá Nhân (0912 345 678)',
    customer_name: 'Vũ Thị Minh',
    customer_phone: '0912345678',
    customer_email: 'minh.vu@miumiusale.com',
    crm_customer_id: undefined, // Potential Lead
    assigned_rep_name: 'Lê Thị Mai (Sale Exec)',
    unread_count: 0,
    status: 'IN_PROGRESS',
    tags: ['Thời Trang Nữ', 'Lazada Ads'],
    last_message: 'Mình gửi hình ảnh mẫu sản phẩm đợt mới về nhờ bên bạn đăng gian hàng.',
    last_message_at: '09:45',
    messages: [
      {
        id: 'm6',
        conversation_id: 'chat_003',
        sender_type: 'CUSTOMER',
        sender_name: 'Vũ Thị Minh',
        content: 'Chị Mai ơi, gian hàng Lazada Thời Trang Miu Miu đợt này đơn về đều chưa?',
        timestamp: '09:40',
        is_read: true,
      },
      {
        id: 'm7',
        conversation_id: 'chat_003',
        sender_type: 'AGENT',
        sender_name: 'Lê Thị Mai (Sale Exec)',
        content: 'Dạ chị Minh! Gian hàng của mình đạt trung bình 120 đơn/ngày ạ. Chị bổ sung thêm mã hàng mới nhé!',
        timestamp: '09:42',
        is_read: true,
      },
      {
        id: 'm8',
        conversation_id: 'chat_003',
        sender_type: 'CUSTOMER',
        sender_name: 'Vũ Thị Minh',
        content: 'Mình gửi hình ảnh mẫu sản phẩm đợt mới về nhờ bên bạn đăng gian hàng.',
        timestamp: '09:45',
        is_read: true,
      },
    ],
  },
];
