import { EcomStore } from '@/types/store';

export const INITIAL_STORES: EcomStore[] = [
  {
    id: 'store_001',
    store_code: 'SHOP-SP-1001',
    store_name: 'Vận Tải Hồng Lực Flagship Store',
    customer_name: 'Trần Thanh Sơn',
    company_name: 'Công ty TNHH Vận Tải Hồng Lực',
    platform: 'Shopee Mall',
    store_url: 'https://shopee.vn/hongluc_official',
    monthly_gmv_actual: 850000000,
    monthly_gmv_target: 800000000,
    health_rating: 'EXCELLENT',
    cancellation_rate_percent: 0.8,
    late_shipment_rate_percent: 1.2,
    rating_score: 4.9,
    owner_ops_name: 'Phạm Minh Đức (Ops Lead)',
    connected_at: '2026-01-15',
  },
  {
    id: 'store_002',
    store_code: 'SHOP-TT-1002',
    store_name: 'Thời Trang An An Official',
    customer_name: 'Nguyễn Thị Hoa',
    company_name: 'Hộ Kinh Doanh Thời Trang An An',
    platform: 'TikTok Shop',
    store_url: 'https://tiktok.com/@anan_fashion',
    monthly_gmv_actual: 450000000,
    monthly_gmv_target: 500000000,
    health_rating: 'GOOD',
    cancellation_rate_percent: 1.5,
    late_shipment_rate_percent: 2.1,
    rating_score: 4.8,
    owner_ops_name: 'Nguyễn Văn Bình (Ops Exec)',
    connected_at: '2026-02-10',
  },
  {
    id: 'store_003',
    store_code: 'SHOP-AM-1003',
    store_name: 'SmartHome Global Direct',
    customer_name: 'Lê Hoàng Anh',
    company_name: 'Công ty CP Gia Dụng SmartHome',
    platform: 'Amazon',
    store_url: 'https://amazon.com/shops/smarthome_global',
    monthly_gmv_actual: 1200000000,
    monthly_gmv_target: 1500000000,
    health_rating: 'WARNING',
    cancellation_rate_percent: 3.2,
    late_shipment_rate_percent: 4.5,
    rating_score: 4.3,
    owner_ops_name: 'Trần Văn Hoàng (Ops Senior)',
    connected_at: '2026-03-01',
  },
];
